language: go

go:
  - "1.12.x"
  - "1.13.x"

sudo: required

go_import_path: github.com/XiaoMi/soar

dist: xenial

services:
  - docker

before_install:
  - docker pull mysql
  - sudo add-apt-repository ppa:duggan/bats --yes
  - sudo apt-get update -qq
  - sudo apt-get install -qq bats

script:
  - make build
  - make docker
  - make cover
  - make test-cli
